<a href="https://colab.research.google.com/github/rizkyageng/KELAS-PSDS-PD4/blob/main/numpy_dan_matriks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
list_1 = [1,2,3,4,5]
arr_1 = np.array([list_1])
arr_1

array([[1, 2, 3, 4, 5]])

In [ ]:
print(np.zeros((2,5))) #membuat array dengan 0 dengan shape (5,5)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
print(np.zeros((5,3))) #membuat array dengan 1 dengan shape (5,5)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print(np.arange(1, 10, 3)) #arange(start, stop, stop)

[1 4 7]


In [ ]:
print(np.linspace(1, 10, 2)) #linspace(start, stop, number)

[ 1. 10.]


In [ ]:
print(np.logspace(1, 10, 2)) #logspace(start, stop, number)

[1.e+01 1.e+10]


In [ ]:
print(np.full((2,2),4)) #membuat array matrix dengan shape (2,2) dengan elemen 99

[[4 4]
 [4 4]]


In [ ]:
A = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(A)

print(np.full_like(A, 4))

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]


In [ ]:
print(np.random.rand(4,2)) #random decimal numbers

[[0.99636363 0.47790691]
 [0.35204636 0.34177577]
 [0.31684491 0.36142502]
 [0.25455295 0.69307909]]


In [ ]:
print(np.random.randint(-4,8, size=(3,3))) #random integer values 

[[ 3 -1  5]
 [-1  7  0]
 [ 4 -2 -3]]


In [ ]:
print(np.identity(5)) # membuat matrix identitas

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
arr = np.array([[1,2,3]]) #membuat matrix dengan perulangan array
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
a=np.array([19, 28, 30], dtype='int32')
print(a)

print("Dimensi dari array a adalah", a.ndim)

[19 28 30]
Dimensi dari array a adalah 1


In [ ]:
b= np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]
